# see https://docs.travis-ci.com/user/languages/php/ for more hints
dist: precise

language: php

php:
  - 7.3
  - 7.4
#  - 8.0
#  - 8.1

addons:
  mariadb: '10.6'

services:
  - mysql
  - postgresql

before_script:
  - sudo mysql -e 'CREATE DATABASE travis_ci_test;'
  - sudo psql -c 'create database travis_ci_test;'
  - composer self-update
  - composer install --no-interaction

script:
  - XDEBUG_MODE=coverage phpunit --configuration phpunit.xml --coverage-clover php-tests/data/clover.xml

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover php-tests/data/clover.xml

env:
  global:
    - PGPORT=5432
    - PGUSER=root
    - PGPASS=
    - PGDB=travis_ci_test
    - MYUSER=root
    - MYPASS=
    - MYDB=travis_ci_test

notifications:
  email: "me@kalanys.com"
